name: b-controlled-box-foreman
version: '0.1.0'
summary: Foreman ROS 2 Package with ctrlX Data Layer integration
description: Package for managing ros2_control component lifecycle using ctrlX non-RT Data Layer
base: core24
confinement: strict

plugs:
  ros-base:
    interface: content
    content: executables
    target: $SNAP/rosruntime
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer
  active-solution:
    interface: content
    content: solutions
    target: $SNAP_COMMON/solutions

apps:
  foreman-node:
    command: bin/entrypoint.sh
    daemon: simple
    plugs:
      - network
      - network-bind
      - datalayer
      - active-solution
      - ros-base

parts:
  foreman-app:
    plugin: dump
    source: ./foreman_snap_install
    stage-packages: 
      - libpython3.12
    override-build: |
      craftctl default

  scripts:
    plugin: dump
    source: .
    organize:
      entrypoint.sh: bin/entrypoint.sh
      foreman.default.env: etc/foreman.default.env
      
lint:
  ignore:
    - library:
        - usr/lib/x86_64-linux-gnu/libpython3.12.so.*