hardware:
  - FrankaHardwareInterface
  - kassow

lifecycle_nodes:
  - dummy_lifecycle_node

goal_states:

  idle:
    controllers:
      joint_state_broadcaster: inactive
      kassow_joint_trajectory_controller: inactive
      franka_joint_trajectory_controller: inactive
    hardware:
      FrankaHardwareInterface: inactive
      kassow: inactive
    lifecycle_nodes:
      dummy_lifecycle_node: inactive

  broadcast_only:
    controllers:
      joint_state_broadcaster: active
      kassow_joint_trajectory_controller: inactive
      franka_joint_trajectory_controller: inactive
    hardware:
      FrankaHardwareInterface: active
      kassow: active
    lifecycle_nodes:
      dummy_lifecycle_node: active

  running:
    controllers:
      joint_state_broadcaster: active
      kassow_joint_trajectory_controller: active
      franka_joint_trajectory_controller: active
    hardware:
      FrankaHardwareInterface: active
      kassow: active
    lifecycle_nodes:
      dummy_lifecycle_node: active
