controller_manager: controller_manager
transition_pause: 0.5
 
base:
  controllers: [joint_state_broadcaster]
  hardware:    [RRBotSystemMultiInterface]
 
running:
  controllers: [joint_state_broadcaster, forward_velocity_controller]
  hardware:    [RRBotSystemMultiInterface]
