from dataclasses import dataclass
from dataclasses import field
from enum import Enum
from typing import Dict, List, Optional
from pathlib import Path

from lifecycle_msgs.msg import State


@dataclass
class ForemanParameters:
    """Holds resolved Foreman parameters."""
    config_path: Path
    # later we can add or other parameters
    # timeout: float = 5.0

class ForemanErrorCategory(Enum):
    """Categories of domain errors the system can encounter."""
    TRANSPORT = "TransportError"                # ROS service timeout, network issue
    EXECUTION = "ExecutionError"              # controller_manager rejected the command
    UNEXPECTED_STATE = "UnexpectedStateError"   # hardware crashed unprompted
    PLANNER = "PlannerError"              # planner disallowed transitions, deadlock in planning
    NONE = "None"


@dataclass
class ForemanError:
    """Domain representation of an error in the system."""
    category: ForemanErrorCategory
    message: str
    component_names: Optional[List[str]] = None

@dataclass
class ForemanResponse:
    """Standardized response for Engine API calls."""
    success: bool
    message: str
    error: Optional[ForemanError] = None

class ComponentType(Enum):
    HARDWARE = 'hardware'
    CONTROLLER = 'controller'
    LIFECYCLE_NODE = 'lifecycle_node'


class LifecycleState(Enum):
    """
    ROS 2 control component lifecycle sequence.

    Based on ROS lifecycle_msgs.State.
    """

    UNCONFIGURED = State.PRIMARY_STATE_UNCONFIGURED
    INACTIVE = State.PRIMARY_STATE_INACTIVE
    ACTIVE = State.PRIMARY_STATE_ACTIVE
    FINALIZED = State.PRIMARY_STATE_FINALIZED

    def __ge__(self, other: 'LifecycleState') -> bool:
        if isinstance(other, LifecycleState):
            return self.value >= other.value
        return NotImplemented

    def __lt__(self, other: 'LifecycleState') -> bool:
        if isinstance(other, LifecycleState):
            return self.value < other.value
        return NotImplemented

    @property
    def ros_state(self) -> State:
        """Generate the ROS 2 message object."""
        labels = {
            1: 'unconfigured',
            2: 'inactive',
            3: 'active',
            4: 'finalized'
        }
        return State(id=self.value, label=labels.get(self.value, 'unknown'))

    def step_towards(self, target: 'LifecycleState') -> Optional['LifecycleState']:
        """Calculate 1 step forward or backward in the sequence."""
        if self == target:
            return None

        sequence = [
            LifecycleState.UNCONFIGURED,
            LifecycleState.INACTIVE,
            LifecycleState.ACTIVE,
            LifecycleState.FINALIZED
        ]
        index_current = sequence.index(self)
        index_target = sequence.index(target)

        if index_current < index_target:
            return sequence[index_current + 1]
        else:
            return sequence[index_current - 1]


@dataclass
class Component:
    """A single hardware interface or a controller we are managing."""

    name: str
    component_type: ComponentType
    lifecycle_state: LifecycleState


@dataclass
class SystemState:
    """Current state of the control system. Populated from ControllerManager::Activity msg."""
    
    components: Dict[str, Component] = field(default_factory=dict)


@dataclass
class HardwareRequirement:
    """Explicitly binds a hardware piece to its minimum required state."""

    name: str
    state: LifecycleState


@dataclass
class ControllerDependencyRule:
    """Defines exactly what hardware must be in what state before controller is active."""

    controller_name: str
    required_hardware: List[HardwareRequirement]


@dataclass
class SystemGoal:
    """Named system goal state. Populated from YAML."""

    name: str
    hardware_goals: List[Component] = field(default_factory=list)
    controller_goals: List[Component] = field(default_factory=list)
    lifecycle_node_goals: List[Component] = field(default_factory=list)


@dataclass
class SystemTransitionCommand:
    """1-step instruction generated by the planner to execute on the ControllerManager."""

    component: Component
    goal_state: LifecycleState

    def __repr__(self):
        c_type = self.component.component_type.value
        return f"TransitionCommand({c_type} '{self.component.name}' -> {self.goal_state.name})"

# System snapshot, mimics flatbuffer schema
@dataclass
class ErrorSnapshot:
    is_error: bool
    category: str
    message: str
    components: List[str]

@dataclass
class ForemanSnapshot:
    goal: str
    ready: bool
    at_goal: bool
    error: ErrorSnapshot
    components: List[Component]